name: Labeler

on:
  pull_request:
    branches:
      - 'test/*'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
